# Job which initializes the deployed MS SQL Server, that is:
#   - Connects to the deployed MS SQL Server
#   - Waits until the MS SQL Server is ready
#   - Runs on it a SQL script that creates sample tables, views and procedures

apiVersion: batch/v1
kind: Job

metadata:
  name: mssql-init

spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: initializer
        image: mcr.microsoft.com/mssql-tools
        command:
        - /bin/bash
        - -c
        # In the below command:
        #   - We wait until the MS SQL server is ready (by trying to execute a SQL query)
        #   - mssql is the metadata.name field from the service.yaml (i.e. the MS SQL Server host name)
        #   - and the init.sql script comes from the init-configmap.yaml
        #   - "sa" is a built-in system administrator account in the MS SQL Server
        args:
        - |
          # Wait until the MS SQL server is ready
          until /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P "$SA_PASSWORD" -Q "SELECT 1" > /dev/null 2>&1; do
            sleep 5
          done

          echo "SQL Server is ready, running the script."

          # Run the init script
          /opt/mssql-tools/bin/sqlcmd \
          -S mssql \
          -U sa \
          -P "$SA_PASSWORD" \
          -i /scripts/init.sql

          echo "Script ran successfully."

        env:
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: SA_PASSWORD

        volumeMounts:
        - name: init-script
          mountPath: /scripts

      volumes:
      - name: init-script
        configMap:
          name: mssql-init-script