apiVersion: v1
kind: Secret

metadata:
  name: {{ .Release.Name }}-secret

type: Opaque

stringData:
  SQL_USER: {{ .Values.secret.SQL_USER | quote }}
  SQL_PASSWORD: {{ .Values.secret.SQL_PASSWORD | quote }}