# rag_workflow.py

from langgraph.graph import StateGraph, START, END

from data_models import RAGState, AskRequest, AskResponse, SearchResult
from interfaces import AnswerModel, SemanticSearchTool


class RAGWorkflow:
    """
    We build here a graph with nodes. The 'state: RAGState' variable is processed by each node one by one and each node 
    adds new fields with data to it.
        
    The 'state: RAGState' variable is the final output of the entire graph obtained when running 'self.graph.ainvoke'
    and it contains the following data fields:
        - retrieved_docs: list[SearchResult]
        - answer: str
    
    Each node contains a function (added using the add_node function) which adds new fields to the 'state' variable.
    """

    def __init__(
        self,
        semantic_search: SemanticSearchTool,
        answer_model: AnswerModel,
    ):
        self.semantic_search = semantic_search
        self.answer_model = answer_model

        self.graph = self._build_graph()



    async def answer(
        self,
        ask_request: AskRequest,
    ) -> AskResponse:
        """
        Run the graph to generate an answer to the question. Return the graph's state.
        """

        result = await self.graph.ainvoke(
            {
                "query": ask_request.query,
                "top_k": ask_request.top_k,
            }
        )

        return AskResponse(
            answer=result['answer'],
            retrieved_docs=result['retrieved_docs'],
        )



    def _build_graph(self):
        "Add nodes to the graph and define in which order nodes process the 'state' variable."

        graph = StateGraph(RAGState)

        graph.add_node("retrieve", self._retrieve)
        graph.add_node("answer", self._answer)

        graph.add_edge(START, "retrieve")
        graph.add_edge("retrieve", "answer")
        graph.add_edge("answer", END)

        return graph.compile()



    async def _retrieve(self, state: RAGState) -> RAGState:
        """
        Function used in nodes to add the 'retrieved_docs' field to the graph's state with data about retrieved documents 
        relevant to the question.
        """

        retrieved_docs: list[SearchResult] = await self.semantic_search.search(
            AskRequest(
                query=state["query"],
                top_k=state["top_k"],
            )
        )
        # retrieved_docs: list[SearchResult] = [
        #     SearchResult(
        #         object_id=1,
        #         text_chunk='test',
        #         similarity_score=0.9,
        #     )
        # ]

        return {
            "retrieved_docs": retrieved_docs,
        }



    async def _answer(self, state: RAGState) -> RAGState:
        """
        Function used in nodes to add the 'answer' field to the graph's state with an answer generated by the model.
        """

        context = "\n\n".join(
            f"Document ID: {doc.object_id}\n"
            f"Similarity: {doc.similarity_score}\n"
            f"Text: {doc.text_chunk}"
            for doc in state["retrieved_docs"]
        )

        prompt = (
            "Answer the question based on the following documents:\n\n"
            f"{context}\n\n"
            f"Question: {state['query']}"
        )

        answer = await self.answer_model.generate(prompt)

        return {
            "answer": answer,
        }