namespace: semantic-search

# Parameters for the RayService resource
rayService:
  name: semantic-search-rayservice  # Name of the created RayService resource
  replicas: 1
  rayVersion: "2.49.1"  # match the Ray version of KubeRay
  headCpu: "2"
  headMemory: "3Gi"
  workerCpu: "2"
  workerMemory: "3Gi"

# Name of the image to use to run the Ray Serve app
image: semantic-search


# Parameters related to the Ray Serve app
app:
  # workingDir - Path to the .zip folder containing all the files needed for the Ray app (this is a path inside the container where we use mounting)
  # fileName - Name of the file with the Ray Serve app (without the .py extension)
  # folderPath - A full path to the folder containing the Ray Serve app in the image
  # boundDeploymentName - Name of the bound deployment - output of the APIClassName.bind() command, where APIClassName is name of the 
  #                       class where we define Rest API endpoints
  workingDir: /app/routes.zip
  fileName: routes
  boundDeploymentName: semantic_search_service


# Environment variables used by the app
env:
  # Whether or not to download a new model for generating embeddings from the Hugging Face (if we don't provide it,
  # we need to have a model saved already and provide a path to it using the MODEL_PATH parameter)
  DOWNLOAD_MODEL: False
  # Path to the ONNX model to use for creating embeddings (this is a path inside the container where we use mounting)
  MODEL_PATH: /app/ml_models/all-MiniLM-L6-v2
  
  # ====================================================================================================
  # Variables related to Milvus, the same as in the 'create_milvus_collection' Helm chart, values.yaml file
  # ====================================================================================================
  
  # IP address or DNS name of the Milvus db where we store documents used for semantic search.
  MILVUS_HOST: milvus
  # Name of the collection in the Milvus db with documents used for semantic search.
  MILVUS_COLLECTION_NAME: my_docs
  # Name of the field in the milvus collection which holds vector embeddings.
  EMBEDDING_FIELD_NAME: embedding
  # Name of the field in the milvus collection which holds metadata
  METADATA_FIELD_NAME: metadata
  # Name of the field in the milvus collection which holds a text chunk
  TEXT_FIELD_NAME: text
  # Name of the field in metadata in the milvus collection which represents an ID of the object which documentation refers to
  OBJECT_ID_FIELD_NAME: object_id

# Parameters regarding mounting Azure File share containing scripts to run in pods.
scriptsMounting:
  enabled: true
  # Path to the folder on the host (kind node) which will be used as a volume. 
  # The same path needs to be provided in the kind-config.yaml file in the nodes[0].extraMounts.containerPath field to 
  # specify which path on the host (which runs kind) will correspond to this path.
  # This path should contain the 'services' folder from the repo on the host.
  hostPath: /services
  # Path to a subfolder in volume with FastAPI routes to run which will be mounted into the /app folder
  subPath: semantic_search