apiVersion: v2
name: semantic-search-rayservice
description: |
  A Helm chart that deploys a RayService with the Ray Serve app serving LangGraph RAG workflow.

  That app needs to be saved in the .zip file.

  We can make requests to the deployed REST API server using the url: `http://<ray-service>-head:8000/search`, where `<ray-service>` is 
  the name of the created RayService resource specified in the rayService.name field in values.yaml.
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  # KubeRay is for creating RayService which will run the Ray Serve app serving LangGraph RAG workflow
  - name: kuberay-operator
    version: 1.4.2
    repository: "https://ray-project.github.io/kuberay-helm/"